USE [NCSS_LDM]
GO

SELECT [natural_key]
      ,[result_source_key]
      ,[prep_code]
      ,[major_element_method]
      ,[aluminum_major_element]
      ,[calcium_major_element]
      ,[iron_major_element]
      ,[potassium_major_element]
      ,[magnesium_major_element]
      ,[manganese_major_element]
      ,[sodium_major_element]
      ,[phosphorus_major_element]
      ,[silicon_major_element]
      ,[strontium_major_element]
      ,[titanium_major_element]
      ,[zirconium_major_element]
      ,[trace_element_method]
      ,[silver_trace_element]
      ,[arsenic_trace_element]
      ,[barium_trace_element]
      ,[beryllium_trace_element]
      ,[cadmium_trace_element]
      ,[cobalt_trace_element]
      ,[chromium_trace_element]
      ,[copper_trace_element]
      ,[mercury_trace_element]
      ,[manganese_trace_element]
      ,[molybdenum_trace_element]
      ,[nickel_trace_element]
      ,[phosphorus_trace_element]
      ,[lead_trace_element]
      ,[antimony_trace_element]
      ,[selenium_trace_element]
      ,[tin_trace_element]
      ,[strontium_trace_element]
      ,[thallium_trace_element]
      ,[vanadium_trace_element]
      ,[tungsten_trace_element]
      ,[zinc_trace_element]
      ,[iron_oxide_total]
      ,[aluminum_oxide_total]
      ,[potassium_oxide_total]
  INTO SDA_Major_And_Trace_Elements_And_Oxides
  FROM [dbo].[Major_And_Trace_Elements_And_Oxides]
GO
CREATE INDEX [natural_key] ON [SDA_Major_And_Trace_Elements_And_Oxides](natural_key)
GO